import { useEffect, useRef, useState } from  'react';
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from "next/router";
import { toast } from 'react-toastify';
// import { loginUser } from '@/redux/features/auth/authSlice';
import MainLayout from "@/components/layouts/MainLayout";
import ButtonUI from '@/components/UI/ButtonUI';
import { Card, Input, InputLabel, FormGroup, CardContent, Typography } from "@mui/material";
import BarChart from '@/components/dashBoard/BarChart';
import PieChart from '@/components/dashBoard/PieChart';
import MyProjectsList from '@/components/dashBoard/MyProjectsList';
import MyTicketsList from '@/components/dashBoard/MyTicketsList';

const Home = () => {
  const effectRan = useRef(false);
  const { isAuthenticated } = useSelector(state => state.auth);
  const [hasMounted, setHasMounted] = useState(false);
  
  // useEffect(() => {
  //   if (effectRan.current === true || process.env.NEXT_PUBLIC_NODE_ENV !== 'development') {
  //   //   console.log('effectRan-inner')
  //   //   console.log(effectRan)
  //   // };
  //   // return () => {
  //   //   console.log('unmounted')
  //   //   effectRan.current = true;
  //   //   console.log('effectRan-02')
  //   //   console.log(effectRan)
  //   // };
  //   }
  // }, []);
  
  useEffect(() => {
    setHasMounted(true);
  }, []);
  
  if (!hasMounted) {
    return null;
  }

  return !isAuthenticated ? (
    <section className="dash">
      <div className="dash__unauth">
        <h3>Please Sign In.</h3>
        <div className="dash__unauth-btns">
          <ButtonUI
            className="dash__unauth-btn"
            variant="contained"
            href="/signin"
          >
            Sign In  
          </ButtonUI>
          <ButtonUI
            className="dash__unauth-btn"
            variant='outlined'
            href="/signup"
          >
            Sign Up
          </ButtonUI>
        </div>
      </div>
    </section>
  ) : (
    <section className="dash">
      <div className="dash__content">
        <Card className="dash__card">
          <div className="dash__heading-sec">
            <div className="dash__header">
              <Typography variant='h6' component='h1'>Tickets by Priority</Typography>
            </div>
          </div>
          <div className="dash__detail">
            <PieChart />
          </div>
        </Card>
        <Card className="dash__card">
          <div className="dash__heading-sec">
            <div className="dash__header">
              <Typography variant='h6' component='h1'>My Tickets</Typography>
            </div>
          </div>
          <div className="dash__detail">
            <div className="dash__list">
              {/* {ticket.tickets.map((ticket, index) => <MyTicketsList ticket={ticket} key={index} />
              )} */}
            </div>
          </div>
        </Card>
        <Card className="dash__card">
          <div className="dash__heading-sec">
            <div className="dash__header">
              <Typography variant='h6' component='h1'>My Projects</Typography>
            </div>
          </div>
          <div className="dash__detail">
            <div className="dash__list">
              {/* {project.projects.map((project, index) => (
                <MyProjectsList project={project} key={index} />
              ))} */}
            </div>
          </div>
        </Card>
        <Card className="dash__card">
          <div className="dash__heading-sec">
            <div className="dash__header">
              <Typography variant='h6' component='h1'>Tickets by Status</Typography>
            </div>
          </div>
          <div className="dash__detail">
            <div className="dash__list">
              <BarChart />
            </div>
          </div>
        </Card>
      </div>
    </section>
  )
};
export default Home;
Home.getLayout = function getLayout(Home) {
  return <MainLayout>{Home}</MainLayout>;
}

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
